;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ammo.Type.Kinetic",DevComment="")
+GameplayTagList=(Tag="Event.GrantRifle",DevComment="")
+GameplayTagList=(Tag="Event.GrantStaff",DevComment="")
+GameplayTagList=(Tag="Event.GrantSword",DevComment="")
+GameplayTagList=(Tag="Faction.Dominion",DevComment="")
+GameplayTagList=(Tag="Faction.Reformation",DevComment="")
+GameplayTagList=(Tag="Narrative.Trigger.Fired",DevComment="")
+GameplayTagList=(Tag="Weapon.FusionCoil",DevComment="")
+GameplayTagList=(Tag="Weapon.Pistol",DevComment="")
+GameplayTagList=(Tag="Weapon.Rifle",DevComment="")
+GameplayTagList=(Tag="Weapon.Staff",DevComment="")
+GameplayTagList=(Tag="Weapon.Sword",DevComment="")

