// SignalForgeLogChannels.cpp

#include "Core/SignalForgeLogChannels.h"

DEFINE_LOG_CATEGORY(LogSignalForge);
DEFINE_LOG_CATEGORY(LogSFCombat);
DEFINE_LOG_CATEGORY(LogSFEquipment);
DEFINE_LOG_CATEGORY(LogSFInventory);
DEFINE_LOG_CATEGORY(LogSFCharacter);
DEFINE_LOG_CATEGORY(LogSFAI);
DEFINE_LOG_CATEGORY(LogSFSave);
DEFINE_LOG_CATEGORY(LogSFUI);
DEFINE_LOG_CATEGORY(LogSFInput);
DEFINE_LOG_CATEGORY(LogSFPlayerClass);
